export const ADD_PRODUCT_LOADING = "ADD_PRODUCT_LOADING"
export const ADD_PRODUCT_SUCCESSFUL = "ADD_PRODUCT_SUCCESSFUL"
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR"

export const GET_PRODUCTS_LOADING = "GET_PRODUCTS_LOADING"
export const GET_PRODUCTS_SUCCESSFUL = "GET_PRODUCTS_SUCCESSFUL"
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR"

export const PRODUCT_TO_DELETE = "PRODUCT_TO_DELETE"
export const PRODUCT_DELETE_SUCCESSFUL = "PRODUCT_DELETE_SUCCESSFUL"
export const PRODUCT_DELETE_ERROR = "PRODUCT_DELETE_ERROR"

export const PRODUCT_TO_EDIT = "PRODUCT_TO_EDIT"
export const PRODUCT_EDIT_SUCCESSFUL = "PRODUCT_EDIT_SUCCESSFUL "
export const PRODUCT_EDIT_ERROR = "PRODUCT_EDIT_ERROR"

