export const ADD_PRODUCT_LOADING = "ADD_PRODUCT_LOADING"
export const ADD_PRODUCT_SUCCESSFUL = "ADD_PRODUCT_SUCCESSFUL"
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR"

export const GET_PRODUCTS_LOADING = "GET_PRODUCTS_LOADING"
export const GET_PRODUCTS_SUCCESSFUL = "GET_PRODUCTS_SUCCESSFUL"
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR"
